package com.jm.oj.dataobject;

public class QuestionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.idquestion
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    private Integer idquestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questionname
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    private String questionname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.questiongroup
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    private String questiongroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.difficulty
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    private Integer difficulty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.idquestion
     *
     * @return the value of question.idquestion
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public Integer getIdquestion() {
        return idquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.idquestion
     *
     * @param idquestion the value for question.idquestion
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public void setIdquestion(Integer idquestion) {
        this.idquestion = idquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questionname
     *
     * @return the value of question.questionname
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public String getQuestionname() {
        return questionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questionname
     *
     * @param questionname the value for question.questionname
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public void setQuestionname(String questionname) {
        this.questionname = questionname == null ? null : questionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.questiongroup
     *
     * @return the value of question.questiongroup
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public String getQuestiongroup() {
        return questiongroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.questiongroup
     *
     * @param questiongroup the value for question.questiongroup
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public void setQuestiongroup(String questiongroup) {
        this.questiongroup = questiongroup == null ? null : questiongroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.difficulty
     *
     * @return the value of question.difficulty
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public Integer getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.difficulty
     *
     * @param difficulty the value for question.difficulty
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }
}