package com.jm.oj.dataobject;

public class StudentDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idStudent
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    private Integer idstudent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idStudent
     *
     * @return the value of student.idStudent
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    public Integer getIdstudent() {
        return idstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idStudent
     *
     * @param idstudent the value for student.idStudent
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    public void setIdstudent(Integer idstudent) {
        this.idstudent = idstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}