package com.jm.oj.jmoj.dataobject;

public class StudentDO extends StudentDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.course
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    private String course;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.course
     *
     * @return the value of student.course
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.course
     *
     * @param course the value for student.course
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }
}