package com.jm.oj.jmoj.dataobject;

public class StudentDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.idStudent
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    private Integer idstudent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.StudentEmail
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    private String studentemail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idStudent
     *
     * @return the value of student.idStudent
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public Integer getIdstudent() {
        return idstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idStudent
     *
     * @param idstudent the value for student.idStudent
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public void setIdstudent(Integer idstudent) {
        this.idstudent = idstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.StudentEmail
     *
     * @return the value of student.StudentEmail
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public String getStudentemail() {
        return studentemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.StudentEmail
     *
     * @param studentemail the value for student.StudentEmail
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    public void setStudentemail(String studentemail) {
        this.studentemail = studentemail == null ? null : studentemail.trim();
    }
}