package com.jm.oj.jmoj.dao;

import com.jm.oj.jmoj.dataobject.StudentDO;
import com.jm.oj.jmoj.dataobject.StudentDOKey;

public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    int deleteByPrimaryKey(StudentDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    StudentDO selectByPrimaryKey(StudentDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 00:12:16 AEST 2020
     */
    int updateByPrimaryKey(StudentDO record);
}