package com.jm.oj.dao;

import com.jm.oj.dataobject.QuestionDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface QuestionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    int deleteByPrimaryKey(Integer idquestion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    int insert(QuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    int insertSelective(QuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    QuestionDO selectByPrimaryKey(Integer idquestion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    int updateByPrimaryKeySelective(QuestionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Mon May 18 08:43:02 AEST 2020
     */
    int updateByPrimaryKey(QuestionDO record);
    QuestionDO selectById(int idquestion);
    void insertQuestion(int id,String questionname,String content,String testcase);
    void updateQuestion(int id,String content);
    void deleteQuestion(int id);
    String searchanswer(int id);
    String testcase(int id);
}