package com.jm.oj.dao;

import com.jm.oj.dataobject.StudentDO;
import com.jm.oj.dataobject.StudentDOKey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int deleteByPrimaryKey(StudentDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    StudentDO selectByPrimaryKey(StudentDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int updateByPrimaryKey(StudentDO record);

    StudentDO selectByEmail(String email);

    void updateByPwd(String email,String newpwd);

    void insertByEmailPwd(String email,String pwd,int id,String groupid,String course,String name,String studentnumber);
}