package com.jm.oj.dao;

import com.jm.oj.dataobject.TeacherDO;
import com.jm.oj.dataobject.TeacherDOKey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TeacherDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int deleteByPrimaryKey(TeacherDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int insert(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int insertSelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    TeacherDO selectByPrimaryKey(TeacherDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int updateByPrimaryKeySelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sun May 17 22:18:46 AEST 2020
     */
    int updateByPrimaryKey(TeacherDO record);

    TeacherDO selectByEmail(String email);

    void updateByPwd(String email,String newpwd);
}